version: "3.9"

services:
  redis:
    image: "redis:6.2-alpine"

  web:
    image: "ghcr.io/made2021-glasses-defect-detection/web-server"
    ports:
      - "8000:8000"    
    environment:
      - REDIS_HOST=redis
      - GUNICORN_CMD_ARGS="--bind=0.0.0.0"
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads

  input_validator:
    image: "ghcr.io/made2021-glasses-defect-detection/input-classifier"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads

volumes:
  uploads: