version: "3"

services:
  redis:
    image: "redis:6.2-alpine"
    command: redis-server --save 30 1
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - redis-data:/data

  web:
    image: "ghcr.io/made2021-glasses-defect-detection/web-server"
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - GUNICORN_CMD_ARGS="--bind=0.0.0.0"
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads

  validation:
    image: "ghcr.io/made2021-glasses-defect-detection/input-classifier"
    restart: always
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads

  segmentation:
    image: "ghcr.io/made2021-glasses-defect-detection/segmentation"
    restart: always
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads

  classification:
    image: "ghcr.io/made2021-glasses-defect-detection/classification"
    restart: always
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads

volumes:
  redis-data:
  uploads:
